////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Dev Services for Apicurio Registry
include::_attributes.adoc[]
:categories: messaging
:summary: Start Apicurio Registry automatically in dev and test modes.
:topics: messaging,kafka,apicurio,registry,dev-services,dev-mode,testing
:extensions: io.quarkus:quarkus-apicurio-registry-avro,io.quarkus:quarkus-messaging-kafka

If an extension for schema registry, such as `quarkus-apicurio-registry-avro` or `quarkus-confluent-registry-avro`, is present, Dev Services for Apicurio Registry automatically starts an Apicurio Registry instance in dev mode and when running tests.
Also, all Kafka channels in SmallRye Reactive Messaging are automatically configured to use this registry.
This automatic configuration only applies to serializers and deserializers from Apicurio Registry serde libraries and Confluent Schema Registry serde libraries, because their properties are set:

[source,properties]
----
# for Apicurio Registry serde
mp.messaging.connector.smallrye-kafka.apicurio.registry.url=http://localhost:8081/apis/registry/v3
# for Confluent Schema Registry serde
mp.messaging.connector.smallrye-kafka.schema.registry.url=http://localhost:8081/apis/ccompat/v7
----


== Enabling / Disabling Dev Services for Apicurio Registry

Dev Services for Apicurio Registry is automatically enabled unless:

- `quarkus.apicurio-registry.devservices.enabled` is set to `false`
- `mp.messaging.connector.smallrye-kafka.apicurio.registry.url` is configured
- `mp.messaging.connector.smallrye-kafka.schema.registry.url` is configured
- all the Reactive Messaging Kafka channels have either the `apicurio.registry.url` attribute or the `schema.registry.url` attribute set

Dev Services for Apicurio Registry relies on Docker to start the registry.
If your environment does not support Docker, you will need to start the registry manually, or use an already running registry.
In such case, you can configure the registry URL for all Kafka channels in SmallRye Reactive Messaging with a single property.
For Apicurio Registry serde, that is:

[source,properties]
----
mp.messaging.connector.smallrye-kafka.apicurio.registry.url=... your Apicurio Registry URL...
----

For Confluent Schema Registry serde, that is:

[source,properties]
----
mp.messaging.connector.smallrye-kafka.schema.registry.url=... your Confluent Schema Registry URL...
----

== Shared registry

Most of the time, you need to share the registry between applications.
Dev Services for Apicurio Registry implements a _service discovery_ mechanism for your multiple Quarkus applications running in _dev_ mode to share a single registry.

NOTE: Dev Services for Apicurio Registry starts the container with the `quarkus-dev-service-apicurio-registry` label, which is used to identify the container.

If you need multiple (shared) registries, you can configure the `quarkus.apicurio-registry.devservices.service-name` attribute and indicate the registry name.
It looks for a container with the same value, or starts a new one if none can be found.
The default service name is `apicurio-registry`.

Sharing is enabled by default in dev mode, but disabled in test mode.
You can disable the sharing with `quarkus.apicurio-registry.devservices.shared=false`.

== Setting the port

By default, Dev Services for Apicurio Registry picks a random port and configures the application.
You can set the port by configuring the `quarkus.apicurio-registry.devservices.port` property.

Note that the Kafka channels in SmallRye Reactive messaging are automatically configured with the chosen port.

== Configuring the image

Dev Services for Apicurio Registry uses `apicurio/apicurio-registry` images. These images use an in-memory h2 database by default.
You can select any 3.x version from https://hub.docker.com/r/apicurio/apicurio-registry:

[source,properties,subs=attributes+]
----
quarkus.apicurio-registry.devservices.image-name=apicurio/apicurio-registry:latest-snapshot
----

== Kafka Connect / Debezium integration

If you use Kafka Connect with Apicurio Registry converters (for example, with Debezium), you can add the `quarkus-apicurio-registry-kafka-connect` extension:

[source,xml,role="primary asciidoc-tabs-target-sync-cli asciidoc-tabs-target-sync-maven"]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-apicurio-registry-kafka-connect</artifactId>
</dependency>
----

This extension provides GraalVM native image support for the Apicurio Registry Kafka Connect converters (`AvroConverter`, `ExtJsonConverter`, `SerdeBasedConverter`).

When Dev Services for Apicurio Registry is active, the registry URL is also exposed as `quarkus.apicurio-registry.kafka-connect.registry-url`, which you can use to configure your Kafka Connect converters:

[source,properties]
----
# Auto-populated by Dev Services
quarkus.apicurio-registry.kafka-connect.registry-url=http://localhost:8081/apis/registry/v3
----

For production use, configure the Apicurio Registry Kafka Connect converters in your connector configuration:

[source,properties]
----
key.converter=io.apicurio.registry.utils.converter.AvroConverter
key.converter.apicurio.registry.url=http://my-registry:8080/apis/registry/v3
key.converter.apicurio.registry.auto-register=true
value.converter=io.apicurio.registry.utils.converter.AvroConverter
value.converter.apicurio.registry.url=http://my-registry:8080/apis/registry/v3
value.converter.apicurio.registry.auto-register=true
----

[[Compose]]
== Compose

The Apicurio Dev Services supports xref:compose-dev-services.adoc[Compose Dev Services].
It relies on a `compose-devservices.yml`, such as:

[source,yaml,subs=attributes+]
----
name: <application name>
services:
  apicurio:
    image: {apicurio-registry-image}
    ports:
      - "8080"
----
